// AUTO-GENERATED by scripts/import-music.mjs — do not edit by hand.
export type Album = {
  id: string;
  artist: string;
  album: string;
  cover: string | null;
  tracks: { title: string; file: string }[];
};
export type Track = { title: string; file: string; album: string; artist: string; cover: string | null };

export const ALBUMS: Album[] = [
  {
    "id": "trova-de-lid-lira-de-dragon",
    "artist": "Trova de Lid",
    "album": "Lira de Dragón",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__cover.jpg",
    "tracks": [
      {
        "title": "Edad y Amor",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__01.mp3"
      },
      {
        "title": "El trovador marcha",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__02.mp3"
      },
      {
        "title": "La lira del Dragón",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__03.mp3"
      },
      {
        "title": "La flor blanca",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__04.mp3"
      },
      {
        "title": "Fábulas de Otoño",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__05.mp3"
      },
      {
        "title": "Despertar entire ninfas",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__06.mp3"
      },
      {
        "title": "Tu recuerdo",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__07.mp3"
      },
      {
        "title": "Lo irreparable",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__08.mp3"
      },
      {
        "title": "Bonus- Splendor Solis",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/trova-de-lid-lira-de-dragon__09.mp3"
      }
    ]
  },
  {
    "id": "dim-compendium-i",
    "artist": "DIM",
    "album": "Compendium I",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__cover.png",
    "tracks": [
      {
        "title": "Edge of Town",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__01.mp3"
      },
      {
        "title": "Woods of Old",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__02.mp3"
      },
      {
        "title": "Sellsword's Grotto",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__03.mp3"
      },
      {
        "title": "Ellendrial's Lullaby",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__04.mp3"
      },
      {
        "title": "Clandestine",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__05.mp3"
      },
      {
        "title": "King's Arrival",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__06.mp3"
      },
      {
        "title": "Farewell (New Lands Await)",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-i__07.mp3"
      }
    ]
  },
  {
    "id": "dim-compendium-v",
    "artist": "DIM",
    "album": "Compendium V",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__cover.jpg",
    "tracks": [
      {
        "title": "Ten Thousand in Bramble",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__01.mp3"
      },
      {
        "title": "The Veil's Allure",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__02.mp3"
      },
      {
        "title": "Mirage of the Path Behind",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__03.mp3"
      },
      {
        "title": "Amber on the Waning Sky",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__04.mp3"
      },
      {
        "title": "Firefly Cathedral",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__05.mp3"
      },
      {
        "title": "Keep to the Lamplit Road",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__06.mp3"
      },
      {
        "title": "Where Trees Frown",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__07.mp3"
      },
      {
        "title": "Lair of Long Silence",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__08.mp3"
      },
      {
        "title": "Glint of a Gleaming Shore (Home)",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-compendium-v__09.mp3"
      }
    ]
  },
  {
    "id": "dim-the-veins-of-a-hidden-stair",
    "artist": "DIM",
    "album": "The Veins of a Hidden Stair",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-the-veins-of-a-hidden-stair__cover.png",
    "tracks": [
      {
        "title": "Sorrow and Death",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-the-veins-of-a-hidden-stair__01.mp3"
      },
      {
        "title": "Hidden Stair",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-the-veins-of-a-hidden-stair__02.mp3"
      },
      {
        "title": "Felled Cavern Beneath a Coarse and Distant Sky",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/dim-the-veins-of-a-hidden-stair__03.mp3"
      }
    ]
  },
  {
    "id": "hellige-malebolge",
    "artist": "Hellige",
    "album": "Malebolge",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__cover.jpg",
    "tracks": [
      {
        "title": "Woman of Blood and Fury",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__01.mp3"
      },
      {
        "title": "Great Scourge",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__02.mp3"
      },
      {
        "title": "THOU ART O'ERTAKEN",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__03.mp3"
      },
      {
        "title": "Malebolge",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__04.mp3"
      },
      {
        "title": "O Wrath Insane...",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__05.mp3"
      },
      {
        "title": "Viewless Winds",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__06.mp3"
      },
      {
        "title": "Kingdom Come",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-malebolge__07.mp3"
      }
    ]
  },
  {
    "id": "hellige-eternal-winds-of-ash-ice",
    "artist": "Hellige",
    "album": "Eternal Winds of Ash & Ice",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__cover.jpg",
    "tracks": [
      {
        "title": "O Sweet Light, Sweet Siren",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__01.mp3"
      },
      {
        "title": "Emerald Flesh",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__02.mp3"
      },
      {
        "title": "Wreath of Kingsfoil",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__03.mp3"
      },
      {
        "title": "Weighted Wings",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__04.mp3"
      },
      {
        "title": "The Snow It Melts the Soonest",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__05.mp3"
      },
      {
        "title": "Forests in Gold",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__06.mp3"
      },
      {
        "title": "Graven Pathways",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/hellige-eternal-winds-of-ash-ice__07.mp3"
      }
    ]
  },
  {
    "id": "gallowbraid-ashen-eidolon",
    "artist": "Gallowbraid",
    "album": "Ashen Eidolon",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/gallowbraid-ashen-eidolon__cover.jpg",
    "tracks": [
      {
        "title": "Ashen Eidolon",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/gallowbraid-ashen-eidolon__01.mp3"
      },
      {
        "title": "Autumn I",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/gallowbraid-ashen-eidolon__02.mp3"
      },
      {
        "title": "Oak and Aspen",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/gallowbraid-ashen-eidolon__03.mp3"
      },
      {
        "title": "Autumn II",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/gallowbraid-ashen-eidolon__04.mp3"
      },
      {
        "title": "Stone of Remembrance",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/gallowbraid-ashen-eidolon__05.mp3"
      }
    ]
  },
  {
    "id": "thurnin-menhir",
    "artist": "Thurnin",
    "album": "Menhir",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__cover.jpg",
    "tracks": [
      {
        "title": "The Voyage",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__01.mp3"
      },
      {
        "title": "Ancient Rites",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__02.mp3"
      },
      {
        "title": "Vicariously, We Rest",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__03.mp3"
      },
      {
        "title": "Vagrants",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__04.mp3"
      },
      {
        "title": "The Oath",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__05.mp3"
      },
      {
        "title": "Forsake Us Not",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__06.mp3"
      },
      {
        "title": "Winds of Decay",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__07.mp3"
      },
      {
        "title": "A Lament for the End",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__08.mp3"
      },
      {
        "title": "Trials of Menhir",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__09.mp3"
      },
      {
        "title": "Fall of Men",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/thurnin-menhir__10.mp3"
      }
    ]
  },
  {
    "id": "elyvilon-bhr006-drums-in-the-deepwood",
    "artist": "Elyvilon",
    "album": "BHR006- Drums in the Deepwood",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__cover.jpg",
    "tracks": [
      {
        "title": "A Great Stirring",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__01.mp3"
      },
      {
        "title": "A Hunger to Carry Off Flocks",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__02.mp3"
      },
      {
        "title": "Just Stones Beneath the Bridge",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__03.mp3"
      },
      {
        "title": "Peikon Luola",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__04.mp3"
      },
      {
        "title": "What Broods Under Deepening Cloudmurk",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__05.mp3"
      },
      {
        "title": "Moss-Laden and Shambling",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__06.mp3"
      },
      {
        "title": "Gristle and Bone, All Turned to Stone",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__07.mp3"
      },
      {
        "title": "Gahanka",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__08.mp3"
      },
      {
        "title": "Drums in the Deepwood",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/elyvilon-bhr006-drums-in-the-deepwood__09.mp3"
      }
    ]
  },
  {
    "id": "nachtwache-sorgen-mac-diu-sela",
    "artist": "Nachtwache",
    "album": "Sorgēn mac diu sēla",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__cover.jpg",
    "tracks": [
      {
        "title": "Hellarūna Intro",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__01.mp3"
      },
      {
        "title": "Sorgēn mac diu sēla",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__02.mp3"
      },
      {
        "title": "Thar uaht thegeno gelih",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__03.mp3"
      },
      {
        "title": "Ih bim āmarlīh",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__04.mp3"
      },
      {
        "title": "Sīn tac piqueme, daz er touuan scal",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__05.mp3"
      },
      {
        "title": "Lietz her heidine man ober seo lidan",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__06.mp3"
      },
      {
        "title": "Feichanig",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__07.mp3"
      },
      {
        "title": "Min herza",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/nachtwache-sorgen-mac-diu-sela__08.mp3"
      }
    ]
  },
  {
    "id": "various-artists-children-of-the-underground-charity-compilation",
    "artist": "Various Artists",
    "album": "Children of The Underground - Charity Compilation",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__cover.png",
    "tracks": [
      {
        "title": "die Puppe der letzten Zuflucht",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__01.mp3"
      },
      {
        "title": "Ночной Бросок",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__02.mp3"
      },
      {
        "title": "Ball of Worms",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__03.mp3"
      },
      {
        "title": "Formless Memories",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__04.mp3"
      },
      {
        "title": "Помни Меня",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__05.mp3"
      },
      {
        "title": "Чёрная Комета",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__06.mp3"
      },
      {
        "title": "Zuflucht der Atem von Marusja",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__07.mp3"
      },
      {
        "title": "Soil Under Nails",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__08.mp3"
      },
      {
        "title": "Maiden in a Crystal Tomb",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__09.mp3"
      },
      {
        "title": "Спи Спокойно (R.I.P A.T)",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__10.mp3"
      },
      {
        "title": "Fozen Sun",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/various-artists-children-of-the-underground-charity-compilation__11.mp3"
      }
    ]
  },
  {
    "id": "tales-under-the-oak-the-toad-king",
    "artist": "TALES UNDER THE OAK",
    "album": "The Toad King",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/tales-under-the-oak-the-toad-king__cover.jpg",
    "tracks": [
      {
        "title": "Birth of the Toad King",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/tales-under-the-oak-the-toad-king__01.mp3"
      },
      {
        "title": "Ancient Wisdom of the Swamps",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/tales-under-the-oak-the-toad-king__02.mp3"
      },
      {
        "title": "Wide Hall's Welcoming Light",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/tales-under-the-oak-the-toad-king__03.mp3"
      },
      {
        "title": "Ruler's Crown",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/tales-under-the-oak-the-toad-king__04.mp3"
      },
      {
        "title": "Eternal Sleep",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/tales-under-the-oak-the-toad-king__05.mp3"
      },
      {
        "title": "Leaving the Frozen Swamp Kingdom",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/tales-under-the-oak-the-toad-king__06.mp3"
      }
    ]
  },
  {
    "id": "velum-lunae-santa-lepra",
    "artist": "Velum Lunae",
    "album": "Santa Lepra",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__cover.png",
    "tracks": [
      {
        "title": "El Altar Bajo el Musgo",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__01.mp3"
      },
      {
        "title": "Epifanía",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__02.mp3"
      },
      {
        "title": "Éxtasis",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__03.mp3"
      },
      {
        "title": "Hiedra",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__04.mp3"
      },
      {
        "title": "El Amparo de la Niebla",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__05.mp3"
      },
      {
        "title": "La Fuente de las Mentiras",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__06.mp3"
      },
      {
        "title": "El Rapto",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__07.mp3"
      },
      {
        "title": "Exvoto",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__08.mp3"
      },
      {
        "title": "El Claro (Luz de Plata)",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__09.mp3"
      },
      {
        "title": "Bajo las Cuatro Torres",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__10.mp3"
      },
      {
        "title": "La Tregua",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__11.mp3"
      },
      {
        "title": "Flagrum",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__12.mp3"
      },
      {
        "title": "La Seña del Ángel",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__13.mp3"
      },
      {
        "title": "Eclipse (Con Dani Dean)",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__14.mp3"
      },
      {
        "title": "La Luna, el Óxido y la Angustia",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__15.mp3"
      },
      {
        "title": "La Luz a Través de sus Estigmas",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/velum-lunae-santa-lepra__16.mp3"
      }
    ]
  },
  {
    "id": "cave-spellcaster-troglodyte",
    "artist": "Cave Spellcaster",
    "album": "Troglodyte",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__cover.jpg",
    "tracks": [
      {
        "title": "Crawler from the Underground",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__01.mp3"
      },
      {
        "title": "Rusty Spear Sharp No More",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__02.mp3"
      },
      {
        "title": "That Hateful Yellow Star",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__03.mp3"
      },
      {
        "title": "A Dance for the Under Gods (feat. Frost Clad)",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__04.mp3"
      },
      {
        "title": "A Moment of Reflection",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__05.mp3"
      },
      {
        "title": "Encapsulated by Primitive Magic",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__06.mp3"
      },
      {
        "title": "Eyeless Fate",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__07.mp3"
      },
      {
        "title": "Lone Dark Tower",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__08.mp3"
      },
      {
        "title": "Deep Sleep by the Underground Lake",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/cave-spellcaster-troglodyte__09.mp3"
      }
    ]
  },
  {
    "id": "iskonge-lone-knight",
    "artist": "Iskonge",
    "album": "Lone Knight",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/iskonge-lone-knight__cover.jpg",
    "tracks": [
      {
        "title": "The Calm in my Refuge",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/iskonge-lone-knight__01.mp3"
      },
      {
        "title": "Hidden Treasure in the Cave",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/iskonge-lone-knight__02.mp3"
      },
      {
        "title": "Ivy Leaves",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/iskonge-lone-knight__03.mp3"
      },
      {
        "title": "Peacefully",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/iskonge-lone-knight__04.mp3"
      },
      {
        "title": "Last Breath of the Dragon",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/iskonge-lone-knight__05.mp3"
      },
      {
        "title": "Lone Knight",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/iskonge-lone-knight__06.mp3"
      }
    ]
  },
  {
    "id": "aethelu-chapter-i-e-p",
    "artist": "Aethelu",
    "album": "Chapter I (e.p.)",
    "cover": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__cover.jpg",
    "tracks": [
      {
        "title": "Tower Hills",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__01.mp3"
      },
      {
        "title": "Spring of Arda",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__02.mp3"
      },
      {
        "title": "Light of the Trees",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__03.mp3"
      },
      {
        "title": "Tower of the Sun",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__04.mp3"
      },
      {
        "title": "Silverlode",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__05.mp3"
      },
      {
        "title": "Golden Wood",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__06.mp3"
      },
      {
        "title": "Mingling of the Lights",
        "file": "https://github.com/marpreal/acorn-and-ink/releases/download/music-v1/aethelu-chapter-i-e-p__07.mp3"
      }
    ]
  }
];

export const TRACKS: Track[] = ALBUMS.flatMap((a) =>
  a.tracks.map((t) => ({ title: t.title, file: t.file, album: a.album, artist: a.artist, cover: a.cover }))
);
