// Extract the chosen albums from ~/Downloads into public/sounds/<album>/ and
// generate src/lib/tracks.ts (albums + flat track list) for the in-app player.
//   node scripts/import-music.mjs
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const DL = path.join(os.homedir(), "Downloads");
const OUT = path.resolve("public/sounds");
const TMP = path.join(os.tmpdir(), "acorn-music");

const WANTED = [
  "Trova de Lid - Lira de Dragón.zip",
  "DIM - Compendium I.zip",
  "DIM - Compendium V.zip",
  "DIM - The Veins of a Hidden Stair.zip",
  "Hellige - Malebolge.zip",
  "Hellige - Eternal Winds of Ash & Ice.zip",
  "Gallowbraid - Ashen Eidolon.zip",
  "Thurnin - Menhir.zip",
  "Elyvilon - BHR006- Drums in the Deepwood.zip",
  "Nachtwache - Sorgēn mac diu sēla.zip",
  "Various Artists - Children of The Underground - Charity Compilation.zip",
  "TALES UNDER THE OAK - The Toad King.zip",
  "Velum Lunae - Santa Lepra.zip",
  "Cave Spellcaster - Troglodyte.zip",
  "Iskonge - Lone Knight.zip",
  "Aethelu - Chapter I (e.p.).zip",
];

const slug = (s) =>
  s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function parseAlbum(zipBase) {
  const name = zipBase.replace(/\.zip$/i, "").replace(/\s*\(\d+\)\s*$/, "");
  const i = name.indexOf(" - ");
  return i === -1 ? { artist: "", album: name } : { artist: name.slice(0, i).trim(), album: name.slice(i + 3).trim() };
}

function trackTitle(mp3) {
  const t = mp3.replace(/\.mp3$/i, "");
  const parts = t.split(" - ");
  const last = parts[parts.length - 1];
  return last.replace(/^\s*\d+\s*[-.)]?\s*/, "").trim() || t;
}

const dl = fs.readdirSync(DL);
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const albums = [];
for (const zipName of WANTED) {
  let zipPath = path.join(DL, zipName);
  if (!fs.existsSync(zipPath)) {
    const base = zipName.replace(/\.zip$/, "");
    const cand = dl.find((f) => f.startsWith(base) && f.endsWith(".zip"));
    if (!cand) { console.warn("⚠ MISSING:", zipName); continue; }
    zipPath = path.join(DL, cand);
  }
  const { artist, album } = parseAlbum(path.basename(zipPath));
  const id = slug(`${artist}-${album}`) || slug(album);
  const dest = path.join(OUT, id);
  const tmp = path.join(TMP, id);
  fs.rmSync(tmp, { recursive: true, force: true });
  fs.mkdirSync(tmp, { recursive: true });
  fs.mkdirSync(dest, { recursive: true });

  execSync(`unzip -o -j ${JSON.stringify(zipPath)} -d ${JSON.stringify(tmp)}`, { stdio: "ignore" });

  const files = fs.readdirSync(tmp);
  const mp3s = files.filter((f) => /\.mp3$/i.test(f)).sort((a, b) => a.localeCompare(b));
  const coverName = files.find((f) => /^cover\.(jpe?g|png)$/i.test(f)) || files.find((f) => /\.(jpe?g|png)$/i.test(f));

  let cover = null;
  if (coverName) {
    const ext = path.extname(coverName).toLowerCase();
    fs.copyFileSync(path.join(tmp, coverName), path.join(dest, "cover" + ext));
    cover = `/sounds/${id}/cover${ext}`;
  }
  const tracks = [];
  mp3s.forEach((m, i) => {
    const num = String(i + 1).padStart(2, "0");
    fs.copyFileSync(path.join(tmp, m), path.join(dest, `${num}.mp3`));
    tracks.push({ title: trackTitle(m), file: `/sounds/${id}/${num}.mp3` });
  });
  fs.rmSync(tmp, { recursive: true, force: true });
  if (tracks.length) { albums.push({ id, artist, album, cover, tracks }); console.log(`✓ ${artist} — ${album}: ${tracks.length} tracks`); }
}

const ts = `// AUTO-GENERATED by scripts/import-music.mjs — do not edit by hand.
export type Album = {
  id: string;
  artist: string;
  album: string;
  cover: string | null;
  tracks: { title: string; file: string }[];
};
export type Track = { title: string; file: string; album: string; artist: string; cover: string | null };

export const ALBUMS: Album[] = ${JSON.stringify(albums, null, 2)};

export const TRACKS: Track[] = ALBUMS.flatMap((a) =>
  a.tracks.map((t) => ({ title: t.title, file: t.file, album: a.album, artist: a.artist, cover: a.cover }))
);
`;
fs.writeFileSync(path.resolve("src/lib/tracks.ts"), ts);
const total = albums.reduce((n, a) => n + a.tracks.length, 0);
console.log(`\nWrote ${albums.length} albums / ${total} tracks → src/lib/tracks.ts`);
